name: CI/CD
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10.12'
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-distutils
        make install
    - name: Format notebooks
      run: make format